# Generated by Django 4.2.7 on 2023-12-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item',
            new_name='name',
        ),
    ]
